# this file is used to configure the training process of lenet model on dataset.
# it is a sample file, you can modify it to fit your own needs.


# 模型配置
model:
  name: "lenet"
  input_size: [28, 28]    # MNIST image size
  num_classes: 10         # 0-9 for MNIST
  grayscale: true         # MNIST is grayscale

# 数据配置
data:
  name: "mnist"
  root: "../datasets/mnist"          # data root path
  batch_size: 64
  num_workers: 4
  transform:
    train:  
      - name: "tensor"              # the training set augmentation
      - name: "RandomRotation"
        degrees: 15
      - name: "Normalize"
        mean: [0.1307]
        std: [0.3081]
    val:                  # the validation set augmentation
      - name: "tensor"
      - name: "Normalize"
        mean: [0.1307]
        std: [0.3081]


training:
  epochs: 10
  device: "cuda"  # or "cpu"
  optimizer:
    type: "adam"
    lr: 0.001
    weight_decay: 0.0001
  lr_scheduler:  # 可选配置
    type: "step"  # or "cosine", "plateau"
    step_size: 5
    gamma: 0.1